from flask import Flask,jsonify, make_response,request,render_template
from functions import heartandstrokeprediction,heartandstrokedatabaseentry,symptomsdatabaseentry,diseaseprediction

app = Flask(__name__)
@app.route('/', methods=['GET'])
def home():
    return "Hello :) This is my API"


@app.route('/heartandstrokeprediction', methods=['GET'])
def heartandstrokepredictiondata():
    try:
        username=request.args.get("username")
        prediction = heartandstrokeprediction(username)
        return make_response(jsonify(prediction), 200)
    except:
        return "Please send a request parameter with username"


@app.route('/diseaseprediction', methods=['GET'])
def diseasepredictiondata():
    try:
        username=request.args.get("username")
        prediction = diseaseprediction(username)
        return make_response(jsonify(prediction), 200)
    except:
        return "Please send a request parameter with username"

@app.route('/heartandstroke', methods=['GET'])
def heartandstrokedata():
        username=request.args.get("username")
        age=request.args.get("age")
        height=request.args.get("height")
        weight=request.args.get("weight")
        gender=request.args.get("gender")
        bloodpressure=request.args.get("bloodpressure")
        diabetes=request.args.get("diabetes")
        smoking=request.args.get("smoking")
        anaemia=request.args.get("anaemia")
        lastcheckup=request.args.get("lastcheckup")
        hypertension=request.args.get("hypertension")
        heartdisease=request.args.get("heartdisease")
        married=request.args.get("married")
        worktype=request.args.get("worktype")
        residencetype=request.args.get("workresidencetype")
        glucoselevel=request.args.get("workresidencetype")
        output=heartandstrokedatabaseentry(username,age,height,weight,gender,bloodpressure,diabetes,smoking,anaemia,lastcheckup,hypertension,heartdisease,married,worktype,residencetype,glucoselevel)
        return output

@app.route('/symptoms', methods=['GET'])
def symptomsdata():
        username=request.args.get("username")
        back_pain=request.args.get("back_pain")
        constipation=request.args.get("constipation")
        abdominal_pain=request.args.get("abdominal_pain")
        diarrhoea=request.args.get("diarrhoea")
        mild_fever=request.args.get("mild_fever")
        yellow_urine=request.args.get("yellow_urine")
        yellowing_of_eyes=request.args.get("yellowing_of_eyes")
        acute_liver_failure=request.args.get("acute_liver_failure")
        fluid_overload=request.args.get("fluid_overload")
        swelling_of_stomach=request.args.get("swelling_of_stomach")
        swelled_lymph_nodes=request.args.get("swelled_lymph_nodes")
        malaise=request.args.get("malaise")
        blurred_and_distorted_vision=request.args.get("blurred_and_distorted_vision")
        phlegm=request.args.get("phlegm")
        throat_irritation=request.args.get("throat_irritation")
        redness_of_eyes=request.args.get("redness_of_eyes")
        sinus_pressure=request.args.get("sinus_pressure")
        runny_nose=request.args.get("runny_nose")
        congestion=request.args.get("congestion")
        chest_pain=request.args.get("chest_pain")
        weakness_in_limbs=request.args.get("weakness_in_limbs")
        fast_heart_rate=request.args.get("fast_heart_rate")
        pain_during_bowel_movements=request.args.get("pain_during_bowel_movements")
        pain_in_anal_region=request.args.get("pain_in_anal_region")
        bloody_stool=request.args.get("bloody_stool")
        irritation_in_anus=request.args.get("irritation_in_anus")
        neck_pain=request.args.get("neck_pain")
        dizziness=request.args.get("dizziness")
        cramps=request.args.get("cramps")
        bruising=request.args.get("bruising")
        obesity=request.args.get("obesity")
        swollen_legs=request.args.get("swollen_legs")
        swollen_blood_vessels=request.args.get("swollen_blood_vessels")
        puffy_face_and_eyes=request.args.get("puffy_face_and_eyes")
        enlarged_thyroid=request.args.get("enlarged_thyroid")
        brittle_nails=request.args.get("brittle_nails")
        swollen_extremeties=request.args.get("swollen_extremeties")
        excessive_hunger=request.args.get("excessive_hunger")
        extra_marital_contacts=request.args.get("extra_marital_contacts")
        drying_and_tingling_lips=request.args.get("drying_and_tingling_lips")
        slurred_speech=request.args.get("slurred_speech")
        knee_pain=request.args.get("knee_pain")
        hip_joint_pain=request.args.get("hip_joint_pain")
        muscle_weakness=request.args.get("muscle_weakness")
        stiff_neck=request.args.get("stiff_neck")
        swelling_joints=request.args.get("swelling_joints")
        movement_stiffness=request.args.get("movement_stiffness")
        spinning_movements=request.args.get("spinning_movements")
        loss_of_balance=request.args.get("loss_of_balance")
        unsteadiness=request.args.get("unsteadiness")
        weakness_of_one_body_side=request.args.get("weakness_of_one_body_side")
        loss_of_smell=request.args.get("loss_of_smell")
        bladder_discomfort=request.args.get("bladder_discomfort")
        foul_smell_of_urine=request.args.get("foul_smell_of_urine")
        continuous_feel_of_urine=request.args.get("continuous_feel_of_urine")
        passage_of_gases=request.args.get("passage_of_gases")
        internal_itching=request.args.get("internal_itching")
        toxic_look_typhos=request.args.get("toxic_look_typhos")
        depression=request.args.get("depression")
        irritability=request.args.get("irritability")
        muscle_pain=request.args.get("muscle_pain")
        altered_sensorium=request.args.get("altered_sensorium")
        red_spots_over_body=request.args.get("red_spots_over_body")
        belly_pain=request.args.get("belly_pain")
        abnormal_menstruation=request.args.get("abnormal_menstruation")
        dischromic_patches=request.args.get("dischromic_patches")
        watering_from_eyes=request.args.get("watering_from_eyes")
        increased_appetite=request.args.get("increased_appetite")
        polyuria=request.args.get("polyuria")
        family_history=request.args.get("family_history")
        mucoid_sputum=request.args.get("mucoid_sputum")
        rusty_sputum=request.args.get("rusty_sputum")
        lack_of_concentration=request.args.get("lack_of_concentration")
        visual_disturbances=request.args.get("visual_disturbances")
        receiving_blood_transfusion=request.args.get("receiving_blood_transfusion")
        receiving_unsterile_injections=request.args.get("receiving_unsterile_injections")
        coma=request.args.get("coma")
        stomach_bleeding=request.args.get("stomach_bleeding")
        distention_of_abdomen=request.args.get("distention_of_abdomen")
        history_of_alcohol_consumption=request.args.get("history_of_alcohol_consumption")
        blood_in_sputum=request.args.get("blood_in_sputum")
        prominent_veins_on_calf=request.args.get("prominent_veins_on_calf")
        palpitations=request.args.get("palpitations")
        painful_walking=request.args.get("painful_walking")
        pus_filled_pimples=request.args.get("pus_filled_pimples")
        blackheads=request.args.get("blackheads")
        scurring=request.args.get("scurring")
        skin_peeling=request.args.get("skin_peeling")
        silver_like_dusting=request.args.get("silver_like_dusting")
        small_dents_in_nails=request.args.get("small_dents_in_nails")
        inflammatory_nails=request.args.get("inflammatory_nails")
        blister=request.args.get("blister")
        red_sore_around_nose=request.args.get("red_sore_around_nose")
        yellow_crust_ooze=request.args.get("yellow_crust_ooze")
        output=symptomsdatabaseentry(username,back_pain,constipation,abdominal_pain,diarrhoea,mild_fever,yellow_urine,yellowing_of_eyes,acute_liver_failure,fluid_overload,swelling_of_stomach,swelled_lymph_nodes,malaise,blurred_and_distorted_vision,phlegm,throat_irritation,redness_of_eyes,sinus_pressure,runny_nose,congestion,chest_pain,weakness_in_limbs,fast_heart_rate,pain_during_bowel_movements,pain_in_anal_region,bloody_stool,irritation_in_anus,neck_pain,dizziness,cramps,bruising,obesity,swollen_legs,swollen_blood_vessels,puffy_face_and_eyes,enlarged_thyroid,brittle_nails,swollen_extremeties,excessive_hunger,extra_marital_contacts,drying_and_tingling_lips,slurred_speech,knee_pain,hip_joint_pain,muscle_weakness,stiff_neck,swelling_joints,movement_stiffness,spinning_movements,loss_of_balance,unsteadiness,weakness_of_one_body_side,loss_of_smell,bladder_discomfort,foul_smell_of_urine,continuous_feel_of_urine,passage_of_gases,internal_itching,toxic_look_typhos,depression,irritability,muscle_pain,altered_sensorium,red_spots_over_body,belly_pain,abnormal_menstruation,dischromic_patches,watering_from_eyes,increased_appetite,polyuria,family_history,mucoid_sputum,rusty_sputum,lack_of_concentration,visual_disturbances,receiving_blood_transfusion,receiving_unsterile_injections,coma,stomach_bleeding,distention_of_abdomen,history_of_alcohol_consumption,blood_in_sputum,prominent_veins_on_calf,palpitations,painful_walking,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze)
        return output

if __name__ == '__main__':
    app.debug = True
    app.run()
